language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'